//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Бипит9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arendas
    {
        public int Id { get; set; }
        public int Id_avto { get; set; }
        public int Id_fio { get; set; }
        public System.DateTime Data_take { get; set; }
        public System.DateTime Data_re { get; set; }
    }
}
