//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Бипит9
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BIPIT3Entities : DbContext
    {
        public BIPIT3Entities()
            : base("name=BIPIT3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Arenda> Arenda { get; set; }
        public virtual DbSet<Arendas> Arendas { get; set; }
        public virtual DbSet<Avto> Avto { get; set; }
        public virtual DbSet<Avtoes> Avtoes { get; set; }
        public virtual DbSet<FIO> FIO { get; set; }
        public virtual DbSet<FIOs> FIOs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
